# Generated by Django 5.1.3 on 2025-12-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingsearch',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='trendingsearch',
            name='original_language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trendingsearch',
            name='poster_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trendingsearch',
            name='release_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trendingsearch',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
