# Generated by Django 5.1.3 on 2025-12-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_trendingsearch_poster_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingsearch',
            old_name='poster_path',
            new_name='poster_url',
        ),
        migrations.RemoveField(
            model_name='trendingsearch',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='trendingsearch',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='trendingsearch',
            name='vote_average',
        ),
    ]
