# Generated by Django 5.1.3 on 2025-12-17 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='MovieInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('is_liked', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movie_interactions',
                'indexes': [models.Index(fields=['user', 'movie_id'], name='movie_inter_user_id_4ec1f7_idx'), models.Index(fields=['user', 'is_liked'], name='movie_inter_user_id_ca0ecd_idx'), models.Index(fields=['user', 'is_saved'], name='movie_inter_user_id_bdf356_idx')],
                'unique_together': {('user', 'movie_id')},
            },
        ),
    ]
