# Generated by Django 5.1.3 on 2025-12-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar_movieinteraction'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movieinteraction',
            name='movie_inter_user_id_ca0ecd_idx',
        ),
        migrations.RemoveField(
            model_name='movieinteraction',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='movieinteraction',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='User rating (0-5 with 0.5 increments)', max_digits=2, null=True),
        ),
        migrations.AddIndex(
            model_name='movieinteraction',
            index=models.Index(fields=['user', 'rating'], name='movie_inter_user_id_628acb_idx'),
        ),
    ]
